### ISSUE TITLE
"read_domtbl" hangs when the input GFF file has lines starting with "#"

### ISSUE THREAD

**Issue by apcamargo** [padlocbio/padloc#12]
I tried to run PADLOC with an input GFF that I generated from a separate Prodigal run. I noticed that the execution stopped at the `read_domtbl` function and, upon further inspection, I discovered that this was being caused by the `comment = '#'` parameter of the `read_tsv` function.

I'm not exactly sure why `comment = '#'` causes this problem, but it might be a good idea to filter lines starting with `#` even if the GFF file is not internally generated by Prodigal.

**Comment by leightonpayne** [comment]
Hi Antônio,

The issue appears to be with the FAA file that `prodigal` generates rather than the GFF. FAA's generated by `prodigal` contain headers with `#` characters which get carried over to the domain table file generated by `hmmsearch`. I assume this breaks the `read_domtbl` function because it then treats these lines as comments, which causes it to hang for some reason. 

I've updated the `read_domtbl` function so it should now be able to handle `#` characters on non-comment lines, which fixes this bug.
